#pragma once
constexpr int drum_names_start = 27;
constexpr char note_names[12][3] = {
    "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"
};
constexpr char drum_names[][20] = {
    "Laser",
    "Whip",
    "Scratch Push",
    "Scratch Pull",
    "Stick Click",
    "Pop",
    "Metronome Click",
    "Metronome Bell",
    "Bass Drum",
    "Kick Drum",
    "Snare Cross Stick",
    "Snare Drum",
    "Hand Clap",
    "Electric Snare Drum",
    "Floor Tom 2",
    "Hi - Hat Closed",
    "Floor Tom 1",
    "Hi - Hat Foot",
    "Low Tom",
    "Hi - Hat Open",
    "Low - Mid Tom",
    "High - Mid Tom",
    "Crash Cymbal",
    "High Tom",
    "Ride Cymbal",
    "China Cymbal",
    "Ride Bell",
    "Tambourine",
    "Splash cymbal",
    "Cowbell",
    "Crash Cymbal 2",
    "Vibraslap",
    "Ride Cymbal 2",
    "High Bongo",
    "Low Bongo",
    "Conga Dead Stroke",
    "Conga",
    "Tumba",
    "High Timbale",
    "Low Timbale",
    "High Agogo",
    "Low Agogo",
    "Cabasa",
    "Maracas",
    "Whistle Short",
    "Whistle Long",
    "Guiro Short",
    "Guiro Long",
    "Claves",
    "High Woodblock",
    "Low Woodblock",
    "Cuica High",
    "Cuica Low",
    "Triangle Mute",
    "Triangle Open",
    "Shaker",
    "Sleigh Bell",
    "Bell Tree",
    "Castanets",
    "Surdu Dead Stroke",
    "Surdu",
    "Snare Drum Rod",
    "Ocean Drum",
    "Snare Drum Brush",
};